/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_LocalJStack */

#ifndef _Included_app_LocalJStack
#define _Included_app_LocalJStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_LocalJStack
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_app_LocalJStack_init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     app_LocalJStack
 * Method:    dumpStack
 * Signature: (Ljava/io/Writer;)V
 */
JNIEXPORT jint JNICALL Java_app_LocalJStack_dumpStack
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
