# https://github.com/gabime/spdlog/blob/v1.x/appveyor.yml
version: 1.0.{build}
# Do not build feature branch with open Pull Requests
#skip_branch_with_pr: true
image: Visual Studio 2017
environment:
  matrix:
    - GENERATOR: '"Visual Studio 17 2022" -A x64'
      BUILD_TYPE: Release
      CXX_STANDARD: 20
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
# build cache to preserve files/folders between builds
cache:
  - ./build/jdks
build_script:
  - cmd: >-
      set

      mkdir build

      cd build

      set PATH=%PATH%;C:\Program Files\Git\usr\bin

      cmake -G %GENERATOR% -D CMAKE_BUILD_TYPE=%BUILD_TYPE% -D CMAKE_CXX_STANDARD=%CXX_STANDARD% ..

      cmake --build . --config %BUILD_TYPE% --target LibLocalJStack

      cd ..

      mvn clean package

test_script:
  - ps: >-
      mkdir -Force ./build/jdks
      
      ./script/testThreadDump.ps1 -jdkPath ./build/jdks -jdkVersions 11.0.26, 17.0.14, 21.0.3 -jarPath ./target/localjstack-0.0.1.jar -dllPath ./build/src/main/cpp/Release/localjstack.dll -download
